# Categorical variables
A **categorical variable** takes only a limited number of values.

* Consider a survey that asks how often you eat breakfast and provides four options: "Never", "Rarely", "Most days", or "Every day". In this case, the data is categorical, because responses fall into a fixed set of categories.
* If people responded to a survey about which what brand of car they owned, the responses would fall into categories like "Honda", "Toyota", and "Ford". In this case, the data is also categorical.

You will get an error if you try to plug these variables into most machine learning models in Python without preprocessing them first. In this tutorial, we'll compare three approaches that you can use to prepare your categorical data.

## Three Approaches
1) Drop Categorical Variables
The easiest approach to dealing with categorical variables is to simply remove them from the dataset. This approach will only work well if the columns did not contain useful information.

2) Label Encoding
Label encoding assigns each unique value to a different integer.
<img src="https://i.imgur.com/tEogUAr.png" alt="Alt text that describes the graphic" title="Title text" />
This approach assumes an ordering of the categories: "Never" (0) < "Rarely" (1) < "Most days" (2) < "Every day" (3).

This assumption makes sense in this example, because there is an indisputable ranking to the categories. Not all categorical variables have a clear ordering in the values, but we refer to those that do as **ordinal variables**. For tree-based models (like decision trees and random forests), you can expect label encoding to work well with ordinal variables.

3) One-Hot Encoding
One-hot encoding creates new columns indicating the presence (or absence) of each possible value in the original data. To understand this, we'll work through an example.
<img src="https://i.imgur.com/TW5m0aJ.png" alt="Alt text that describes the graphic" title="Title text" />
In the original dataset, "Color" is a categorical variable with three categories: "Red", "Yellow", and "Green". The corresponding one-hot encoding contains one column for each possible value, and one row for each row in the original dataset. Wherever the original value was "Red", we put a 1 in the "Red" column; if the original value was "Yellow", we put a 1 in the "Yellow" column, and so on.

In contrast to label encoding, one-hot encoding does not assume an ordering of the categories. Thus, you can expect this approach to work particularly well if there is no clear ordering in the categorical data (e.g., "Red" is neither more nor less than "Yellow"). We refer to categorical variables without an intrinsic ranking as **nominal variables**.

One-hot encoding generally does not perform well if the categorical variable takes on a large number of values (i.e., you generally won't use it for variables taking more than 15 different values).

In [24]:
import pandas as pd
import os
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [6]:
data = pd.read_csv(os.path.join('melb_data.csv'), index_col=0)

In [7]:
# Separate target from predictors
y = data.Price
X = data.drop(['Price'], axis=1)

In [9]:
# Divide data into training and validation subsets
X_train_full, X_valid_full, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=0)

In [11]:
# Drop columns with missing values (simplest approach)
cols_with_missing = [col for col in X_train_full.columns if X_train_full[col].isnull().any()] 
X_train_full.drop(cols_with_missing, axis=1, inplace=True)
X_valid_full.drop(cols_with_missing, axis=1, inplace=True)

In [12]:
# "Cardinality" means the number of unique values in a column
# Select categorical columns with relatively low cardinality (convenient but arbitrary)
low_cardinality_cols = [cname for cname in X_train_full.columns if X_train_full[cname].nunique() < 10 and 
                        X_train_full[cname].dtype == "object"]

In [13]:
low_cardinality_cols

['Type', 'Method', 'Regionname']

In [14]:
# Select numerical columns
numerical_cols = [cname for cname in X_train_full.columns if X_train_full[cname].dtype in ['int64', 'float64']]

In [16]:
numerical_cols

['Rooms',
 'Distance',
 'Postcode',
 'Bedroom2',
 'Bathroom',
 'Landsize',
 'Lattitude',
 'Longtitude',
 'Propertycount']

In [15]:
# Keep selected columns only
my_cols = low_cardinality_cols + numerical_cols
X_train = X_train_full[my_cols].copy()
X_valid = X_valid_full[my_cols].copy()

In [17]:
X_train.head()

,Type,Method,Regionname,Rooms,Distance,Postcode,Bedroom2,Bathroom,Landsize,Lattitude,Longtitude,Propertycount
Suburb,,,,,,,,,,,,
St Kilda,u,S,Southern Metropolitan,1,5.0,3182.0,1.0,1.0,0.0,-37.85984,144.9867,13240.0
Williamstown,h,SA,Western Metropolitan,2,8.0,3016.0,2.0,2.0,193.0,-37.85800,144.9005,6380.0
Sunshine,h,S,Western Metropolitan,3,12.6,3020.0,3.0,1.0,555.0,-37.79880,144.8220,3755.0
Glenroy,u,SP,Northern Metropolitan,3,13.0,3046.0,3.0,1.0,265.0,-37.70830,144.9158,8870.0
Sunshine North,h,S,Western Metropolitan,3,13.3,3020.0,3.0,1.0,673.0,-37.76230,144.8272,4217.0

Next, we obtain a list of all of the categorical variables in the training data.

We do this by checking the data type (or **dtype**) of each column. The `object` dtype indicates a column has text (there are other things it could theoretically be, but that's unimportant for our purposes). For this dataset, the columns with text indicate categorical variables.

In [18]:
# Get list of categorical variables
s = (X_train.dtypes == 'object')
object_cols = list(s[s].index)

In [19]:
print("Categorical variables:")
print(object_cols)

Categorical variables:
['Type', 'Method', 'Regionname']

## Define Function to Measure Quality of Each Approach
We define a function `score_dataset()` to compare the three different approaches to dealing with categorical variables. This function reports the [mean absolute error](https://en.wikipedia.org/wiki/Mean_absolute_error) (MAE) from a random forest model. In general, we want the MAE to be as low as possible!

In [21]:
# Function for comparing different approaches
def score_dataset(X_train, X_valid, y_train, y_valid):
    model = RandomForestRegressor(n_estimators=100, random_state=0)
    model.fit(X_train, y_train)
    preds = model.predict(X_valid)
    return mean_absolute_error(y_valid, preds)

## Score from Approach 1 (Drop Categorical Variables)
We drop the object columns with the `select_dtypes()` method.

In [22]:
drop_X_train = X_train.select_dtypes(exclude=['object'])
drop_X_valid = X_valid.select_dtypes(exclude=['object'])

print("MAE from Approach 1 (Drop categorical variables):")
print(score_dataset(drop_X_train, drop_X_valid, y_train, y_valid))

MAE from Approach 1 (Drop categorical variables):
175703.48185157913

## Score from Approach 2 (Label Encoding)
Scikit-learn has a `LabelEncoder` class that can be used to get label encodings. We loop over the categorical variables and apply the label encoder separately to each column.

In [25]:
# Make copy to avoid changing original data 
label_X_train = X_train.copy()
label_X_valid = X_valid.copy()

# Apply label encoder to each column with categorical data
label_encoder = LabelEncoder()
for col in object_cols:
    label_X_train[col] = label_encoder.fit_transform(X_train[col])
    label_X_valid[col] = label_encoder.transform(X_valid[col])

print("MAE from Approach 2 (Label Encoding):") 
print(score_dataset(label_X_train, label_X_valid, y_train, y_valid))

MAE from Approach 2 (Label Encoding):
165936.40548390493

In the code cell above, for each column, we randomly assign each unique value to a different integer. This is a common approach that is simpler than providing custom labels; however, we can expect an additional boost in performance if we provide better-informed labels for all ordinal variables.

## Score from Approach 3 (One-Hot Encoding)
We use the `OneHotEncoder` class from scikit-learn to get one-hot encodings. There are a number of parameters that can be used to customize its behavior.

* We set `handle_unknown='ignore'` to avoid errors when the validation data contains classes that aren't represented in the training data, and
* setting `sparse=False` ensures that the encoded columns are returned as a numpy array (instead of a sparse matrix).

To use the encoder, we supply only the categorical columns that we want to be one-hot encoded. For instance, to encode the training data, we supply `X_train[object_cols]`. (`object_cols` in the code cell below is a list of the column names with categorical data, and so `X_train[object_cols]` contains all of the categorical data in the training set.)

In [26]:
from sklearn.preprocessing import OneHotEncoder

# Apply one-hot encoder to each column with categorical data
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(X_train[object_cols]))
OH_cols_valid = pd.DataFrame(OH_encoder.transform(X_valid[object_cols]))

# One-hot encoding removed index; put it back
OH_cols_train.index = X_train.index
OH_cols_valid.index = X_valid.index

# Remove categorical columns (will replace with one-hot encoding)
num_X_train = X_train.drop(object_cols, axis=1)
num_X_valid = X_valid.drop(object_cols, axis=1)

# Add one-hot encoded columns to numerical features
OH_X_train = pd.concat([num_X_train, OH_cols_train], axis=1)
OH_X_valid = pd.concat([num_X_valid, OH_cols_valid], axis=1)

print("MAE from Approach 3 (One-Hot Encoding):") 
print(score_dataset(OH_X_train, OH_X_valid, y_train, y_valid))

MAE from Approach 3 (One-Hot Encoding):
166089.4893009678

In [27]:
num_X_train

,Rooms,Distance,Postcode,Bedroom2,Bathroom,Landsize,Lattitude,Longtitude,Propertycount
Suburb,,,,,,,,,
St Kilda,1,5.0,3182.0,1.0,1.0,0.0,-37.85984,144.98670,13240.0
Williamstown,2,8.0,3016.0,2.0,2.0,193.0,-37.85800,144.90050,6380.0
Sunshine,3,12.6,3020.0,3.0,1.0,555.0,-37.79880,144.82200,3755.0
Glenroy,3,13.0,3046.0,3.0,1.0,265.0,-37.70830,144.91580,8870.0
Sunshine North,3,13.3,3020.0,3.0,1.0,673.0,-37.76230,144.82720,4217.0
Balwyn,5,9.7,3103.0,5.0,2.0,611.0,-37.81160,145.07890,5682.0
Pascoe Vale,4,9.9,3044.0,4.0,2.0,250.0,-37.73190,144.94610,7485.0
Sunshine West,3,13.5,3020.0,3.0,1.0,700.0,-37.78450,144.81310,6763.0
Seddon,3,6.6,3011.0,3.0,1.0,283.0,-37.80640,144.89440,2417.0
Altona,4,13.8,3018.0,3.0,1.0,725.0,-37.86780,144.81600,5301.0
Williamstown,2,8.0,3016.0,2.0,1.0,0.0,-37.85040,144.89240,6380.0
Bentleigh East,3,13.9,3165.0,3.0,1.0,596.0,-37.92510,145.07710,10969.0
North Melbourne,2,2.3,3051.0,2.0,1.0,0.0,-37.79880,144.94780,6821.0
Mill Park,5,17.9,3082.0,5.0,2.0,574.0,-37.66936,145.05413,10529.0
Brunswick West,1,5.9,3055.0,1.0,1.0,0.0,-37.77630,144.94700,7082.0
Hadfield,3,12.1,3046.0,3.0,2.0,560.0,-37.71360,144.93740,2606.0
Coburg,3,7.8,3058.0,3.0,1.0,702.0,-37.73910,144.98120,11204.0
Sunshine West,3,13.5,3020.0,3.0,3.0,699.0,-37.78720,144.79750,6763.0
Maribyrnong,3,8.7,3032.0,3.0,2.0,210.0,-37.77320,144.87900,4918.0
Fitzroy North,4,3.5,3068.0,3.0,2.0,445.0,-37.78600,144.98640,6244.0
Bentleigh East,3,13.9,3165.0,3.0,1.0,642.0,-37.92690,145.07870,10969.0
Fitzroy North,5,3.5,3068.0,5.0,2.0,818.0,-37.77490,144.98640,6244.0
Hawthorn East,3,7.5,3123.0,2.0,1.0,0.0,-37.84140,145.05050,6482.0
Northcote,4,5.5,3070.0,4.0,2.0,355.0,-37.76360,144.98720,11364.0
Caroline Springs,3,14.8,3023.0,3.0,2.0,194.0,-37.72530,144.74840,7719.0
Kingsbury,5,12.1,3083.0,5.0,3.0,544.0,-37.71499,145.02967,1414.0
Noble Park,3,22.7,3174.0,3.0,1.0,587.0,-37.96968,145.16832,11806.0
Reservoir,2,11.2,3073.0,2.0,1.0,82.0,-37.69830,145.01040,21650.0
Glen Iris,4,9.2,3146.0,4.0,3.0,1258.0,-37.85520,145.08200,10412.0
Essendon,3,8.0,3040.0,3.0,1.0,862.0,-37.73990,144.89640,9264.0
...,...,...,...,...,...,...,...,...,...
Chadstone,3,13.6,3148.0,4.0,2.0,515.0,-37.88370,145.10600,3582.0
Coburg North,4,9.2,3058.0,4.0,2.0,302.0,-37.72710,144.98420,3445.0
Footscray,3,6.4,3011.0,3.0,1.0,272.0,-37.79770,144.90400,7570.0
Prahran,2,4.5,3181.0,2.0,1.0,98.0,-37.85010,144.99530,7717.0
Reservoir,3,11.2,3073.0,3.0,3.0,618.0,-37.71540,144.99620,21650.0
Doncaster,3,13.9,3108.0,3.0,1.0,651.0,-37.78270,145.10510,9028.0
Sunshine North,3,13.3,3020.0,3.0,1.0,581.0,-37.76020,144.83160,4217.0
Fawkner,3,12.4,3060.0,3.0,1.0,602.0,-37.71440,144.97370,5070.0
Templestowe Lower,2,13.8,3107.0,2.0,1.0,340.0,-37.75640,145.11950,5420.0
Keilor East,3,11.7,3033.0,3.0,1.0,597.0,-37.73305,144.86526,5629.0
Balwyn,4,9.7,3103.0,4.0,3.0,1148.0,-37.80880,145.09910,5682.0
Glenroy,4,11.2,3046.0,4.0,2.0,1017.0,-37.70705,144.91011,8870.0
Glenroy,5,13.0,3046.0,5.0,4.0,695.0,-37.70280,144.93770,8870.0
Coburg,2,7.8,3058.0,2.0,1.0,136.0,-37.74490,144.97540,11204.0
Elsternwick,2,8.5,3185.0,2.0,1.0,0.0,-37.88380,145.00950,4898.0
Hawthorn East,1,6.2,3123.0,1.0,1.0,0.0,-37.83270,145.05428,6482.0
Fitzroy North,3,3.5,3068.0,4.0,1.0,475.0,-37.77860,144.98460,6244.0
Bentleigh,3,13.0,3204.0,3.0,2.0,418.0,-37.91720,145.04210,6795.0
Keilor East,3,12.8,3033.0,3.0,1.0,254.0,-37.74800,144.86300,5629.0
Aberfeldie,3,9.1,3040.0,3.0,2.0,496.0,-37.75590,144.89910,1543.0
St Kilda,2,6.1,3182.0,2.0,1.0,0.0,-37.86260,144.98180,13240.0
North Melbourne,2,2.3,3051.0,2.0,2.0,146.0,-37.79590,144.94640,6821.0
Glen Iris,2,9.2,3146.0,2.0,1.0,97.0,-37.86370,145.06320,10412.0
McKinnon,4,11.4,3204.0,4.0,2.0,568.0,-37.90688,145.02827,2397.0
Prahran,3,4.5,3181.0,3.0,2.0,183.0,-37.85620,145.00420,7717.0
Brunswick,3,5.2,3056.0,3.0,1.0,212.0,-37.77695,144.95785,11918.0
Heidelberg Heights,3,10.5,3081.0,3.0,1.0,748.0,-37.74160,145.04810,2947.0
Coburg,4,6.7,3058.0,4.0,2.0,441.0,-37.73572,144.97256,11204.0
Reservoir,3,12.0,3073.0,3.0,1.0,606.0,-37.72057,145.02615,21650.0
Footscray,4,6.4,3011.0,4.0,2.0,319.0,-37.79430,144.88750,7570.0

## Which approach is best?
In this case, dropping the categorical columns (**Approach 1**) performed worst, since it had the highest MAE score. As for the other two approaches, since the returned MAE scores are so close in value, there doesn't appear to be any meaningful benefit to one over the other.

In general, one-hot encoding (**Approach 3**) will typically perform best, and dropping the categorical columns (**Approach 1**) typically performs worst, but it varies on a case-by-case basis.